### ISSUE TITLE
Additional configurations for RestockPlus

### ISSUE THREAD

**Issue by mwerle** [codepoetpbowden/ConnectedLivingSpace#117]
User Grokit [from the forums](https://forum.kerbalspaceprogram.com/index.php?/topic/192130-111-connected-living-spaces-adopted-2006-2020-12-29/&do=findComment&comment=4025831) provided the following patch:

`@PART[Mk2Pod]:HAS[!MODULE[ModuleConnectedLivingSpace]]:NEEDS[ReStockPlus,SquadExpansion]
{
	MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
		impassablenodes = top
	}
}
@PART[landerCabinSmall]:HAS[!MODULE[ModuleConnectedLivingSpace]]:NEEDS[ReStockPlus]
{
	MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
	}
}`

**Comment by PapaJoesSoup** [comment]
Merged #118 into 2.0.2.1
