### ISSUE TITLE
While building a ship, CLS highlighting breaks

### ISSUE THREAD

**Issue by mwerle** [codepoetpbowden/ConnectedLivingSpace#121]
## Issue
In the Editor, when adding or removing parts from a ship, the CLS highlighting will break and not correctly show the currently selected Living Space.

### Condition:
KSP v1.12.x
CLS v2.0.2.0

In Editor with a vessel consisting of one or more Living Spaces.  Have CLS window open and a Living Space selected which is correctly highlighted.

### Action:
Add or remove a part.

### Actual Result:
Vessel's CLS spaces are incorrectly highlighted.

Specifically, it seems only structural parts and docking ports which are part of a Livving Space are highlighted, parts which can contain Crew are no longer highlighted.

### Expected Result:
The selected Living Space of the vessel is correctly highlighted.

## Workaround:
Toggle highlighting on/off in the CLS UI for the Living Space. It will now be highlighted correctly.

## Additional Notes:
This may be an issue in the way KSP handles highlighting in the editor in general.

With CLS closed, on mouse-over a part, the part and all of its children are highlighted.

Now click-drag the current vessel's root part. When letting go of the mouse button, only the vessels' non-habitable parts are highlighted while the mouse remains over the vessel's root part. Moving the mouse off the root part performs proper highlighting again.

**Comment by PapaJoesSoup** [comment]
Merged into 2.0.2.1
