### ISSUE TITLE
Mk2 Landercan passable nodes

### ISSUE THREAD

**Issue by Bezzier** [codepoetpbowden/ConnectedLivingSpace#123]
Currently, it seems that the [mk2LanderCabin_v2] has impassable nodes on bottom, which makes some lander and station configurations unusable.  I have attached two examples that I in fact built in game before realizing that I had created impassable living spaces.  

Of course I've changed it since then, in my personal copy, but I can't be the only one looking to do this sort of construction.

I would suggest that either by default, or in the freedom config, the bottom node should be passable.

![2022-06-18 (10)](https://user-images.githubusercontent.com/10356756/174416333-6b40f286-3f22-4f52-9401-dbd67a10ff5a.png)

![2022-06-18 (9)](https://user-images.githubusercontent.com/10356756/174416324-8f9307f4-59f2-4c50-9840-9d85fc22b122.png)
.

**Comment by PapaJoesSoup** [comment]
I can see where this might be useful, but a lander can is really designed to be light weight.  If we make it passable, then some weight penalty should be applied  somewhere between 10% - 20%.  Then I could add it to the Freedom config...  Also the V2 version has nose and bottom impassable.  Should the Nose be passable as well (for stacking purposes)?

**Comment by PapaJoesSoup** [comment]
Merged changes into 2.0.2.1
