### ISSUE TITLE
HGR config is incomplete

### ISSUE THREAD

**Issue by codepoetpbowden** [codepoetpbowden/ConnectedLivingSpace#22]
The CLS config for HGR only includes one part. It needs to be reworked.

**Comment by Kerbas-ad-astra** [comment]
My PR #61 adds the capsules with stack attach nodes. Do you think the structural adapters should also be passable?

**Comment by PapaJoesSoup** [comment]
Sorry for ignoring this... is this still valid?

**Comment by Kerbas-ad-astra** [comment]
You merged the PR, so this can be closed.
