### ISSUE TITLE
Module text composition.

### ISSUE THREAD

**Issue by qm3ster** [codepoetpbowden/ConnectedLivingSpace#62]
"but" and "and" are used the wrong way around. Examples:

Can't stay but **can't** pass.
Can't stay and **can** pass.
Can stay but **can** pass.
Can stay and **can't** pass.

**Comment by PapaJoesSoup** [comment]
Can you provide a bit more detail?  such as, is this the rmb info display in the VAB/SPH?

**Comment by qm3ster** [comment]
In the VAB, in the part list, when you mouse over or right click a part, there's the description. On the right of that, there's a scrollable columns where all the modules go (hence topic). Those modules have a title and a property text. For the CLS module, this text is generated incorrectly relative to the actual module properties configured for the part.

**Comment by PapaJoesSoup** [comment]
thanks.  I'll take a close look at that.

**Comment by PapaJoesSoup** [comment]
The verbiage used has been updated with release v1.2.0.0
