### ISSUE TITLE
Mk1 Crew Cabin isn't CLS compatible

### ISSUE THREAD

**Issue by jlcarneiro** [codepoetpbowden/ConnectedLivingSpace#67]
Although I connect a Mk1 Cockpit to a Mk1 Crew Cabin, I can't move kerbals from one to another, neither through stock transfer, nor through ShipManifest transfer...

**Comment by ShotgunNinja** [comment]
This is because the bottom of the Mk1 is not passable. Its by design, as it looks impassable. If you want you can override this behaviour by writing the following in a .cfg file, and putting that .cfg file inside GameData/ directory:
`@PART[mk1pod]
{
  @MODULE[ConnectedLivingSpace]
  {
     @impassablenodes = top
  }
}
`

**Comment by PapaJoesSoup** [comment]
These parts are now passable with release v1.2.3.0.
