### ISSUE TITLE
[1.1.2] NRE when combined w/Karibou Rover & RPM

### ISSUE THREAD

**Issue by KSAMissionCtrl** [codepoetpbowden/ConnectedLivingSpace#70]
This NRE shows up in the log when USI's Karibou rover and its dependencies are loaded with the stock Squad folder, CLS and Rasterprop Monitor (nothing else, other than MM). All mods *and* dependencies were downloaded direct from their Github repositories so versions are latest as of today:

    [EXC 22:56:32.575] NullReferenceException: Object reference not set to an instance of an object
      PartModuleList.Contains (Int32 classID)
      PartModuleList.Contains (System.String className)
      ConnectedLivingSpace.CLSAddon.AddModuleToParts ()
      UnityEngine.Debug:LogException(Exception)
      ConnectedLivingSpace.CLSAddon:AddModuleToParts()
      ConnectedLivingSpace.CLSAddon:Start()

[output_log.txt](https://github.com/codepoetpbowden/ConnectedLivingSpace/files/248099/output_log.txt)

I've also just seen similar behavior with the USI Otter minisub

**Comment by PapaJoesSoup** [comment]
Corrected in 1.2.1.2.  Closed
