### ISSUE TITLE
Packaging/versioning goof

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [codepoetpbowden/ConnectedLivingSpace#78]
Both CLSDefaultPart.cfg.txt and CLSDefaultPart.cfg ended up in the distribution, when it looks like it shouldn't be enabled going by the repo.

(Also, I think the logic's inverted -- the intent is to make any part that is an engine or fuel tank or size 0 impassable, right?  What's it supposed to do?)

**Comment by PapaJoesSoup** [comment]
thanks.  I thought I checked that before publishing... darn.  
and it is intended to make passable candidate parts except engine, fuel tanks or size 0 parts.

**Comment by PapaJoesSoup** [comment]
active config removed.  Corrected in ver 1.2.4.1

**Comment by Kerbas-ad-astra** [comment]
Fixed, thanks!
