### ISSUE TITLE
Mod not appearing in CKAN

### ISSUE THREAD

**Issue by Bezzier** [codepoetpbowden/ConnectedLivingSpace#89]
Believe this is because the NetKAN file in https://github.com/KSP-CKAN/NetKAN uses a $kref to spacedock, and the spacedock file shows 1.3.0 as the latest version supported.

If you either override the version, or point it to GitHub and add a .version here, it should reappear for those using 1.3.1.

@PapaJoesSoup I'll be happy to submit a pull to add the version info here and one to CKAN to change the $kref

Is there any reason this won't work with 1.3.1?

**Comment by PapaJoesSoup** [comment]
@linuxgurugamer released a beta version for 1.3.1 per our agreement.  It will remain beta until I can return from vacation in China.  No updates to ckan will occur until then.  Check the CL thread for the beta release

**Comment by Bezzier** [comment]
Thanks for the quick response. No problem.

**Comment by linuxgurugamer** [comment]
@PapaJoesSoup The only issue is that any other mods which may depend on this won't be available via CKAN easily.
Any idea when you will be back?

**Comment by PapaJoesSoup** [comment]
I'm due backq nov 27

**Comment by PapaJoesSoup** [comment]
Im ok with an update to allow xkan use.  However I am not near a computer and cannot merge.  This would mean an alternative do location, only to have it reverted when I return.  More work for the ckan team

**Comment by linuxgurugamer** [comment]
If you are ok with it, then I'll point CKAN to my repo.
To make it easier, I'll  increment the version of the mod.

**Comment by linuxgurugamer** [comment]
@PapaJoesSoup 
I've updated CKAN with my repo for now (at least, trying to, having a build error right now).
I've also done a PR for you, with the changes I made.  Essentially, I had merged a few PRs which were waiting for you to merge.
Even if you don't use it, you will need to update the version of the mod because I had to do that, currently it is 1.2.5.4

**Comment by PapaJoesSoup** [comment]
That works.  I'll sort it all on my return.  Thanks for your efforts!

**Comment by PapaJoesSoup** [comment]
Correcting KSP version file.  closing.
