### ISSUE TITLE
Localization: forced string order and punctuation may prohibit translation for some languages

### ISSUE THREAD

**Issue by cake-pie** [codepoetpbowden/ConnectedLivingSpace#96]
The offending line is [CLSAddon.cs#L526](https://github.com/codepoetpbowden/ConnectedLivingSpace/blob/0a166124078e6c7cfa41f41acc511948fc15aaf4/plugins/ConnectedLivingSpace/CLSAddon.cs#L526).

The forced order of the individual substrings that make up the entire sentence may prevent a correct translation in some languages if the target language grammar requires a different ordering of the words.

That line also forces punctuation characters for colon ":" and period "." which may not be appropriate for all languages. (e.g. zh-cn and ja terminate sentences with "。")

Ideally, [ConnectedLivingSpace.cfg#L18-L20](https://github.com/codepoetpbowden/ConnectedLivingSpace/blob/0a166124078e6c7cfa41f41acc511948fc15aaf4/Distribution/GameData/ConnectedLivingSpace/Localization/ConnectedLivingSpace.cfg#L18-L20) should just be a single string:

`#clsloc_014a = <color=orange>CLS has prevented the transfer of: <<1>>. <<2>> and <<3>> are not in the same living space.</color>`

**Comment by PapaJoesSoup** [comment]
Corrected string assembly.  Updated translations.
